### PR TITLE
Always set dom->thread to 0 after a pthread join.

### LINKED ISSUE #12: assert in dynamic_free
Hey @Dridi,

We caught this assert today:

```
"Assert error in dynamic_free(), vmod_dynamic.c line 506:
  Condition((dom->thread) == 0) not true.
Backtrace:
  0x43e6d0: pan_backtrace+0x1d
  0x43eb27: pan_ic+0x2f3
  0x7abdfedfa32e: libvmod_dynamic.so(+0x232e) [0x7abdfedfa32e]
  0x7abdfedfb54b: libvmod_dynamic.so(vmod_event+0x31b) [0x7abdfedfb54b]
  0x7abd29304219: vgc.so(+0x2e219) [0x7abd29304219]
  0x44d354: vcl_failsafe_event+0x223
  0x44d881: vcl_set_state+0x366
  0x44e3de: VCL_Poll+0xb1
  0x41cfba: cli_cb_before+0x6c
  0x7fcd16dac0b4: libvarnish.so(+0x80b4) [0x7fcd16dac0b4]

"
```

### PR DESCRIPTION
**Pull request by felipewd**
After a pthread_join we need to guarantee that dom->thread is set to 0
to avoid problems in dynamic_free.

To avoid copy+paste problems, let's do this in a simple function.

Fixes #12

### CODE REVIEW

**Comment by Dridi** [comment]
Thanks again for helping so much. However, I don't think it fixes #12, it will only hide the race shown by the assert. I will thoroughly review this patch next week.

**Comment by felipewd** [comment]
Hey @Dridi, it think it actually fixes.

In the old code, dom->thread = 0 is not set after pthread_join the purged_domains threads. Only in the active_domains threads the code does dom->thread = 0.

Since the steps should be the same when purging a domain thread, we isolated them in a function and called it for both lists.

**Comment by Dridi** [comment]
Hi @felipewd,

Happy new year! Regarding my previous comment, I assumed it was a race but it's simply the thread reset missing in one place. I pushed a different patch for various reasons, including trivial things like naming.

Please give it a spin and feel free to close this PR if it works under load.

Thanks!

**Comment by felipewd** [comment]
hey @Dridi, Happy new year!

Thanks for the review and your complete patch. 

We're going to deploy your solution next week and give it a spin. :)

Thanks a lot!

**Pull request closed without merging**
